import serviceAccount from "./firebase-service.json" with { type: "json" };
import userScheema from "../Models/UserSchema.js";
import { admin } from "./fcmprovaider.js";
import { webPush } from "./webpush.js";
// import { sendIosVoipPush } from "./sendIosVoipPush.js";
import mongoose from "mongoose";

const userSocketMap = {}; // userId => socketId
const busyUsers = {};      // userId → true/false
const pendingCalls = {};        // callId -> callData
const pendingCallsByRoom = {};  // roomName -> callData (same object, second index)

export default function setupVideoCall(io) {
  const videoIO = io.of('/videocall');
  
  videoIO.on("connection", (socket) => {
    console.log("VideoCall socket connected:", socket.id);

    socket.on("register-user", (userId) => {
      userSocketMap[userId] = socket.id;
      console.log("User registered:", userId, socket.id);
    });

    socket.on("user-busy", (data, callback) => {
        const { receiverId } = data;
        // ✅ Bug 1 fix: use === true so only explicitly-set busy flags match
        const receiverBusy = busyUsers[receiverId] === true;
  
        console.log("Busy check:", receiverId, "->", receiverBusy);
  
        callback({
          busy: receiverBusy,
          message: receiverBusy
            ? "User is currently in another call"
            : "User is free to receive call"
        });
      });

    socket.on("initiate-video-call", async(data) => {
      const { roomName, callerId, callerName, receiverId } = data;
      
      const receiverSocket = userSocketMap[receiverId];

      const callId = new mongoose.Types.ObjectId().toString();

      // ✅ FIX: index the pending call by BOTH callId and roomName.
      // callId is only ever sent to the receiver (B), never back to the
      // caller (A). roomName is generated by A locally and is always
      // available to A — so it's used to look the call up when A cancels.
      const callData = {
          callId,
          roomName,
          callerId,
          receiverId,
          createdAt: Date.now(),
      };
      pendingCalls[callId] = callData;
      pendingCallsByRoom[roomName] = callData;

      // if (!receiverSocket) {
      //   socket.emit("user-offline", "User is offline");
      //   return;
      // }
      if (receiverSocket) {
      busyUsers[callerId] = true;
      busyUsers[receiverId] = true;
      videoIO.to(receiverSocket).emit("incoming-video-call", {
        roomName,
        callerName,
        callerId,
        callId,
      });

      console.log("Incoming call sent to:", receiverId);
      return
    }
    const receiver = await userScheema.findById(receiverId);
    if (!receiver?.fcmToken) {
      delete pendingCalls[callId];
      delete pendingCallsByRoom[roomName];
      socket.emit("user-offline", "User unavailable");
      return;
    }
   if(receiver.platform==='android'){
    busyUsers[callerId] = true;
    await admin.messaging().send({
      token: receiver.fcmToken,
    
      data: {
        type: "video_call",
        roomName: String(roomName),
        callId: String(callId),
        callerId: String(callerId),
        callerName: String(callerName),
      },
      android: {
        priority: "high",
        ttl: 30000,
     
      },
    });
    return
   }
  //  if (receiver.platform === "ios" && receiver.voipToken) {
  //   await sendIosVoipPush({
  //     voipToken: receiver.voipToken,
  //     roomName,
  //     callerId,
  //     callerName,
  //     callType: "video_call",
  //   });
  //return
  // }
  await webPush({
    fcmToken: receiver.fcmToken,
     roomName,
     callerId,
     callerName,
     callType: "video_call",
   })
    console.log("Push sent for incoming call");
  
    });
    
  socket.on("call-accepted",async (data) => {
    const { callerId, callId } = data;
      const callerSocket = userSocketMap[callerId];

      // ✅ Clean up both indexes together
      const acceptedCall = pendingCalls[callId];
      if (acceptedCall) delete pendingCallsByRoom[acceptedCall.roomName];
      delete pendingCalls[callId];

      busyUsers[socket.userId] = true;
      if (callerSocket) {
        videoIO.to(callerSocket).emit("call-accepted", {
          message: "Call accepted",
          callId,
        });
        console.log("Call accepted by receiver");
      }
    });

    
    socket.on("video-call-canceled", async(data) => {
      const { receiverId, receiverName, callerName, callerId, callId, roomName } = data;
      const receiverSocket = userSocketMap[receiverId];

      // ✅ Bug 1 fix: delete BOTH sides so neither is stuck as busy
      delete busyUsers[callerId];
      delete busyUsers[receiverId];

      if (receiverSocket) {
        if (callId) delete pendingCalls[callId];
        if (roomName) delete pendingCallsByRoom[roomName];

        videoIO.to(receiverSocket).emit("video-call-ended", {
            receiverId: callerId,
            receiverName: callerName
        });

        console.log("Video call cancelled — busy flags cleared for", callerId, receiverId);
        return;
      }

      // ✅ FIX (root cause of the "B keeps ringing" bug): A never receives
      // callId back from the server, so callId is always undefined here.
      // Look the pending call up by roomName instead — A always has that,
      // since it generated it locally when starting the call.
      const foundCall = roomName ? pendingCallsByRoom[roomName] : null;

      if (foundCall) {
        delete pendingCalls[foundCall.callId];
        delete pendingCallsByRoom[roomName];

        const receiver = await userScheema.findById(receiverId);

        if (receiver?.fcmToken) {
          await admin.messaging().send({
              token: receiver.fcmToken,
              data: {
                  type: "cancel_call",
                  callId: foundCall.callId,
                  roomName: String(roomName),
                  callType: "video_call"
              }
          });
          console.log("cancel_call FCM sent for room:", roomName);
        }
      } else {
        console.log("Pending call not found for room:", roomName);
      }

      console.log("Video call cancelled — busy flags cleared for", callerId, receiverId);
    });

   
    socket.on("call-rejected", (data) => {
      const { callerId, receiverName, currentUserId, callId } = data;
      const callerSocket = userSocketMap[callerId];

      // ✅ Bug 1 fix: clear busy flags for both parties on rejection
      delete busyUsers[callerId];
      delete busyUsers[currentUserId];

      // ✅ Clean up both indexes together
      const rejectedCall = pendingCalls[callId];
      if (rejectedCall) delete pendingCallsByRoom[rejectedCall.roomName];
      delete pendingCalls[callId];

      if (callerSocket) {
        videoIO.to(callerSocket).emit("call-rejected", {
          message: `${receiverName} rejected your call`
        });
      }
    });

    
    socket.on("invite-to-call", (data) => {
      const { roomName, callerId, callerName, receiverId, receiverName } = data;

      const receiverSocket = userSocketMap[receiverId];

      if (!receiverSocket) {
        socket.emit("user-offline", `${receiverName} is offline`);
        return;
      }
      busyUsers[receiverId] = true;

      videoIO.to(receiverSocket).emit("incoming-video-call", {
        roomName,
        callerName,
        callerId
      });

      console.log(`Invited ${receiverId} to room ${roomName}`);
    });

    
    socket.on("participant-joined-call", (data) => {
      socket.broadcast.emit("participant-joined-call", data);
    });

    socket.on("participant-left-call", (data) => {
      socket.broadcast.emit("participant-left-call", data);
    });

    
    socket.on("disconnect", () => {
      console.log("VideoCall socket disconnected:", socket.id);
      for (const [userId, sockId] of Object.entries(userSocketMap)) {
        if (sockId === socket.id) {
          delete userSocketMap[userId];
          delete busyUsers[userId];
          break;
        }
      }
    });
  });
};